name: domain
description: Domain layer of the clients CRUD app.
version: 1.0.0
homepage:

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  dartz: ^0.10.1

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.0
  mockito: ^5.2.0
  test: ^1.16.0
